DEVOIR DE Dii-Toma Dtorg TABLISSI

SOUMIS LE 28/10/2022 A 04:40


ECERVICE 1



In [101]:
print("\nPROGRAMME DERETMINANT LENBRE DIVISIBLE PAR 7 ET NON MULTIPLE DE 5 COMPRIS ENTRE 2000 ET 2300.\n\n") # informer l'utilisateur de l'utilité de la fonction
nbre = 0 # c'est une variable qui servira a savoir le nombre de nombre trouve en tout
for i in range(2000, 2300, 1) :   # parcour de 2000 a 2300 par incrementation de 1
    if (i%7==0) :                 # verificaion si ce nombre est divisible par 7
        if (i%5!=0) :             # verification si ce nombre n'est pas divisible par 5
            nbre = nbre + 1       # Incrementation du nbre
            if (nbre==1) :        # verification si nous somme au premier nombre corespondant a notre recherche
                print("La liste des Nombres de 2000 A 2300 divisible par 7 mais non multiple de 5 sont :\n") # Phrase introductive de la liste
            print("  "+str(nbre)+"-) "+str(i)+"\n") # affichage de chaque nombre trouvé
print("\033[92m NOUS AVONS AU TOTAL "+ str(nbre) + " NOMBRE TROUVE.\n")


PROGRAMME DERETMINANT LENBRE DIVISIBLE PAR 7 ET NON MULTIPLE DE 5 COMPRIS ENTRE 2000 ET 2300.


La liste des Nombres de 2000 A 2300 divisible par 7 mais non multiple de 5 sont :

  1-) 2002

  2-) 2009

  3-) 2016

  4-) 2023

  5-) 2037

  6-) 2044

  7-) 2051

  8-) 2058

  9-) 2072

  10-) 2079

  11-) 2086

  12-) 2093

  13-) 2107

  14-) 2114

  15-) 2121

  16-) 2128

  17-) 2142

  18-) 2149

  19-) 2156

  20-) 2163

  21-) 2177

  22-) 2184

  23-) 2191

  24-) 2198

  25-) 2212

  26-) 2219

  27-) 2226

  28-) 2233

  29-) 2247

  30-) 2254

  31-) 2261

  32-) 2268

  33-) 2282

  34-) 2289

  35-) 2296

 NOUS AVONS AU TOTAL 35 NOMBRE TROUVE.



/-----------------------------------------------------------------/

EXERCICE 2



In [105]:
print("\nPROGRAMME DERETMINANT LE FACTORIEL D'UN NOMBRE.\n\n") # informer l'utilisateur de l'utiliTé de la fonction
nbreFac = int(input("Veuillez entrer le nombre : \n"))         # recuperer le nombre ches l'utilisateur
if (nbreFac == 0 or nbreFac == 1) :
    print("\033[92m Factoriel de " + str(nbreFac) + " est : 1")
else :
    resultatFac = ""                                 # pour l'ecriture de l'operation
    resultatReel = 1                                 # pour la valeur
    for i in range(nbreFac, 0, -1) :                 # parcour de 1 a la valeur entré par décrementation de -1
        resultatReel = resultatReel * i              # operation de calcul
        if(resultatFac == "") :                      # verifier si nous somme a la premiere iteration
            resultatFac = resultatFac + str(i)
        else :
            resultatFac = resultatFac +" x "+ str(i) # concatenatio de l'operation a afficher a LA FIN
    # '\033[92m' qui sera dans la ligne suite est la couleur qui sera donner a l'ecrirutre de la reponse
    # lien de ma recherche de couleur "https://www.delftstack.com/fr/howto/python/python-print-colored-text/"
    print("Le Factoriel de "+str(nbreFac) + " est : " +resultatFac+"\n\n\033[92m DONC NOUS AVONS : Factoriel de ("+str(nbreFac) + ") = " +str(resultatReel))


PROGRAMME DERETMINANT LE FACTORIEL D'UN NOMBRE.


Veuillez entrer le nombre : 
0
 Factoriel de 0 est : 1


/----------------------------------------------------------------/

EXERCICE 3


In [78]:
print("\nPROGRAMME DERETMINANT LE LE CARRE DE TOUT LES NOMBRE DE 1 A LA VALEUR ENTREE.\n\n") # informer l'utilisateur de l'utiliTé de la fonction
nbreFac = int(input("Veuillez entrer le nombre : \n"))       # recuperer le nombre ches l'utilisateur
resultatFac = "NOTRE DICTIONNAIRE EST : {"
for i in range(1, nbreFac+1, 1) :
    if (i<nbreFac) :
        resultatFac = resultatFac + str(i) +" : "+ str(i*i)+", "
    else :
        resultatFac = resultatFac + str(i) +" : "+ str(i*i) +" }"
print ("\n\033[92m" + resultatFac)


PROGRAMME DERETMINANT LE LE CARRE DE TOUT LES NOMBRE DE 1 A LA VALEUR ENTREE.


Veuillez entrer le nombre : 
5

NOTRE DICTIONNAIRE EST : {1 : 1, 2 : 4, 3 : 9, 4 : 16, 5 : 25 }



/--------------------------------------------------------------------------/

EXERCICE 4


In [89]:
print("\nPROGRAMME PERMETTANT DE SUPPRIMER UN CARACTERE D'UN CHAINE DONNEE.\n\n") # informer l'utilisateur de l'utiliTé de la fonction
carChaine =(input("Veuillez entrer la chaine :\n\n"))                             # recuperer la chaine de l'utilisateur
if (carChaine != "") :     # verification si la valeur entre n'est pas vide
    longChaine = len(carChaine)
    indiceCar = int(input("\nVeuillez entrer l'indice du  caractere a supprime de la chaine compris entre 1 et "+ str(longChaine)+" : \n\n"))
    if (indiceCar > longChaine or (indiceCar<1)) :
        print("Desolé la valeur "+str(indiceCar)+" entrée pour la suppression ne correspond pas a L'intervalle")
    else :
        nouvelChaine = "" # compilation des caractere sans celui a supprimer
        for i in range(0, (longChaine), 1) :
            if (i != (indiceCar-1)) :
                nouvelChaine = nouvelChaine + carChaine[i]
        print("\n\033[92mLa Chaine sans la valeur a la position "+str(indiceCar)+" de la chaine de base '"+carChaine+"' est :\n\n    "+nouvelChaine + "\n\n")



PROGRAMME PERMETTANT DE SUPPRIMER UN CARACTERE D'UN CHAINE DONNEE.


Veuillez entrer la chaine :

samson delklkl

Veuillez entrer l'indice du  caractere a supprime de la chaine compris entre 1 et 14 : 

5

La Chaine sans la valeur a la position 5 de la chaine de base 'samson delklkl' est :

    samsn delklkl




/--------------------------------------------------------------------------/

EXERCICE 5


In [106]:
import numpy as np
print("\nPROGRAMME PERMETTANT DE CONVERTIR UN TABLEAU [[0 1] [2 3] [4 5]] EN LISTE [[0, 1], [2, 3], [4, 5]] \n") # informer l'utilisateur de l'utiliTé de la fonction
tabOrg = np.array([[0, 1], [2, 3], [4, 5]])     # tableau d'origine
print("\nLE TABLEAU D'ORIGINE EST : \n")
print(tabOrg)                                   # Affichage du tableau d'origine
print("\n\033[92mLE TABLEAU A LISTE EST : \n")  #'\033[92m' est la couleur vert
print(tabOrg.tolist())                          # LA Fonction to_list est remplacé par tolist


PROGRAMME PERMETTANT DE CONVERTIR UN TABLEAU [[0 1] [2 3] [4 5]] EN [[0, 1], [2, 3], [4, 5]] 


LE TABLEAU D'ORIGINE EST : 

[[0 1]
 [2 3]
 [4 5]]

LE TABLEAU A LISTE EST : 

[[0, 1], [2, 3], [4, 5]]



/--------------------------------------------------------------------------/

EXERCICE 6

In [85]:
import numpy as np
print("\nPROGRAMME PERMETTANT DE CALCULER LA COVARIANCE\n") # informer l'utilisateur de l'utiliTé de la fonction
tab1 = np.array([0, 1, 2])
tab2 = np.array([2, 1, 0])
  
print("\nTABLEAU D'ORIGINE 1\n")
print(tab1)
  
print("\nTABLEAU D'ORIGINE 2\n")
print(tab2)
print("\n\033[92mLA MATRICE COVARIANCE DU TABLEAU 1 ET 2 EST :\n\n", np.cov(tab1, tab2)) # une autre facon d'afficher caihne et entier


PROGRAMME PERMETTANT DE CALCULER LA COVARIANCE


TABLEAU D'ORIGINE 1

[0 1 2]

TABLEAU D'ORIGINE 2

[2 1 0]

LA MATRICE COVARIANCE DU TABLEAU 1 ET 2 EST :

 [[ 1. -1.]
 [-1.  1.]]



/--------------------------------------------------------------------------/

EXERCICE 7

In [7]:
from math import *

print("\nPROGRAMME PERMETTANT DE CALCULER LA RACINE CARRE D'UNE OPERATION\n") # informer l'utilisateur de l'utiliTé de la fonction
C = 50
H = 30
carChaine =(input("Veuillez entrer la ou les valeurs(séparé par des virgules. EXEMPLE : 45,36,78,) :\n\n"))
tabValEntree = (carChaine.split(',')) # recherche sur split 'https://python.developpez.com/faq/?page=String#strSplit'
nbreVal = len(tabValEntree)
for i in range(1, (nbreVal+1), 1) :
    if ((tabValEntree[i-1]!=0) and (tabValEntree[i-1]!="")) :
        D = int(tabValEntree[i-1])
        Q = sqrt((2*C*D)/H)
        partiDecimal = Q - round(Q) # round() fonction d'extraction de la partie entière
        if (partiDecimal == 0) :
            Q = round(Q)
        print("\n\033[90m L'OPERATION "+ str(i) +" AVEC "+ str(D) +" :\n\n\033[92m Q = Racine carrée de [(2 *"+ str(C) +"*" + str(D) +")/" + str(H) + "] \n Q = " + str(Q))



PROGRAMME PERMETTANT DE CALCULER LA RACINE CARRE D'UNE OPERATION

Veuillez entrer la ou les valeurs(séparé par des virgules. EXEMPLE : 45,36,78,) :

100,120,150,180

 L'OPERATION 1 AVEC 100 :

 Q = Racine carrée de [(2 *50*100)/30] 
 Q = 18.257418583505537

 L'OPERATION 2 AVEC 120 :

 Q = Racine carrée de [(2 *50*120)/30] 
 Q = 20

 L'OPERATION 3 AVEC 150 :

 Q = Racine carrée de [(2 *50*150)/30] 
 Q = 22.360679774997898

 L'OPERATION 4 AVEC 180 :

 Q = Racine carrée de [(2 *50*180)/30] 
 Q = 24.49489742783178
